blogApp/urls.py
from django.urls import path
from . import views

app_name = 'blogApp'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('blogs/', views.blogs, name='blogs'),
    path('blog/<int:blog_id>', views.blog, name='blog'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogApp.urls')),
    path('tinymce/', include('tinymce.urls')),
]

blogApp/models.py
from django.db import models
from django.contrib.auth.models import User
from tinymce import models as tinymce_models


# this model will hold the tags of each posts
class Tag(models.Model):
    tag_name = models.CharField(max_length=20, blank=False)

    def __str__(self):
        return self.tag_name


# this model will hold the posts
class Article(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField(max_length=200, blank=False)
    body = tinymce_models.HTMLField(blank=False)
    image_url = models.URLField(max_length=2000, blank=False)
    active = models.BooleanField(default=False)
    featured = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False, blank=False)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.title

blogApp/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from .models import Article


# Create your views here.
def home(request):
    all_blog_items = Article.objects.filter(active=True, featured=True).order_by('-timestamp')[:4]
    author_name = User.get_full_name
    context = {
        'items': all_blog_items,
        'author_name': author_name,
    }
    return render(request, 'blogApp/home.html', context)


def about(request):
    return render(request, 'blogApp/about.html', {})


def blogs(request):
    # this is for the latest blogs
    latest_blog = Article.objects.filter(active=True).last()

    # this is for all the active blogs published
    all_items = Article.objects.filter(active=True).order_by('-timestamp')[1:]

    context = {
        'latest_item': latest_blog,
        'items': all_items,
    }
    return render(request, 'blogApp/blogs.html', context)


def blog(request, blog_id):
    item = get_object_or_404(Article, pk=blog_id)
    context = {
        'item': item
    }
    return render(request, 'blogApp/blog.html', context)

blogApp/templates/blogApp/about.html
{% extends 'base.html' %} {% load static %} {% block title %}
<title>About</title>
{% endblock title %} {% block content %}
<div>
  <!-- this is the main about section -->
  <div class="my-10">
    <h2 class="font-bold text-6xl font-RobotoMono text-gray-700 dark:text-gray-200">Hello there!</h2>
    <p class="my-4">
      This is the blog site I made using Python and Django. <br />
      You might not see much here but I built this website with the following
      technologies:
    </p>
    <div>
      <!-- front-end technologies goes here -->
      <div class="my-5">
        <h3 class="font-bold font-RobotoMono mb-4">Front-End</h3>
        <!-- cards container -->
        <div class="px-4 md:px-10 grid grid-cols-2 gap-5 md:grid-cols-4">
          <!-- cards go here -->
          <div
            class="text-center px-2 py-4 rounded-lg bg-gray-50 shadow-md hover:shadow-lg dark:bg-slate-700"
          >
            <img
              class="mx-auto w-8 h-8 sm:w-10 sm:h-10"
              src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg"
              alt="html5"
            />
            <h4 class="text-gray-700 font-semibold mt-2 dark:text-gray-200">HTML</h4>
          </div>

          <div
            class="text-center px-2 py-4 rounded-lg bg-gray-50 shadow-md hover:shadow-lg dark:bg-slate-700"
          >
            <img
              class="mx-auto w-8 h-8 sm:w-10 sm:h-10"
              src="https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original-wordmark.svg"
              alt="css3"
            />
            <h4 class="text-gray-700 font-semibold mt-2 dark:text-gray-200">CSS</h4>
          </div>

          <div
            class="text-center px-2 py-4 rounded-lg bg-gray-50 shadow-md hover:shadow-lg dark:bg-slate-700"
          >
            <img
              class="mx-auto w-8 h-8 sm:w-10 sm:h-10"
              src="https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg"
              alt="javascript"
            />
            <h4 class="text-gray-700 font-semibold mt-2 dark:text-gray-200">JavaScript</h4>
          </div>

          <div
            class="text-center px-2 py-4 rounded-lg bg-gray-50 shadow-md hover:shadow-lg dark:bg-slate-700"
          >
            <img
              class="mx-auto w-8 h-8 sm:w-10 sm:h-10"
              src="https://www.vectorlogo.zone/logos/tailwindcss/tailwindcss-icon.svg"
              alt="tailwind"
            />
            <h4 class="text-gray-700 font-semibold mt-2 dark:text-gray-200">Tailwind CSS</h4>
          </div>
        </div>
      </div>

      <!-- back-end technologies goes here -->
      <div class="my-5">
        <h3 class="font-bold font-RobotoMono mb-4">Back-End</h3>
        <!-- cards container -->
        <div class="px-4 md:px-10 grid grid-cols-3 gap-5">
          <!-- cards go here -->
          <div
            class="text-center px-2 py-4 rounded-lg bg-gray-50 shadow-md hover:shadow-lg dark:bg-slate-700"
          >
            <img
              class="mx-auto w-8 h-8 sm:w-10 sm:h-10"
              src="https://raw.githubusercontent.com/devicons/devicon/master/icons/python/python-original.svg"
              alt="python"
            />
            <h4 class="text-gray-700 font-semibold mt-2 dark:text-gray-200">Python</h4>
          </div>

          <div
            class="text-center px-2 py-4 rounded-lg bg-gray-50 shadow-md hover:shadow-lg dark:bg-slate-700"
          >
            <img
              class="mx-auto w-9 h-9 sm:w-10 sm:h-10"
              src="https://static.djangoproject.com/img/logos/django-logo-positive.svg"
              alt="django"
            />
            <h4 class="text-gray-700 font-semibold mt-2 dark:text-gray-200">Django</h4>
          </div>

          <div
            class="text-center px-2 py-4 rounded-lg bg-gray-50 shadow-md hover:shadow-lg dark:bg-slate-700"
          >
            <img
              class="mx-auto w-8 h-8 sm:w-10 sm:h-10"
              src="https://www.vectorlogo.zone/logos/sqlite/sqlite-icon.svg"
              alt="sqlite"
            />
            <h4 class="text-gray-700 font-semibold mt-2 dark:text-gray-200">SQLite</h4>
          </div>
        </div>
      </div>
    </div>

    <p class="mt-10">
      The secret ingredient in making this website is 💜, a lot of 💜. <br />
      If you love what you are doing it becomes like your very own pet that
      you'll try to nurture.
    </p>
  </div>

  <!-- this is the section about the graphics that I used -->
  <div class="my-10">
    <h2 class="font-bold font-RobotoMono text-5xl text-gray-700 dark:text-gray-200">The Amazing Illustrations</h2>
    <p class="mt-4">
      All the amazing astronaut illustrations in this website has been made by
      the super talented
      <strong class="text-purple-600"
        ><a href="https://www.freepik.com/catalyststuff"
          >@catalyststuff</a
        ></strong
      >. <br />
      <br />
      Check the very lovely works over at
      <a href="https://www.freepik.com/" class="text-purple-700 font-bold"
        >Freepik</a
      >.
      <br />
      <br />
      Here are some of the amazing artworks:
    </p>
    <!-- here goes the artist artworks -->

    <!-- artworks container -->
    <div class="grid grid-cols-3 gap-2 my-4 px-2 md:px-8">
      <!-- art cards go here | insert context data here -->
      <!-- this is the first artwork -->
      <div>
        <a
          href="https://www.freepik.com/free-vector/happy-astronaut-jumping-cartoon-vector-icon-illustration-science-technology-icon-concept-isolated-premium-vector-flat-cartoon-style_18790456.htm#query=astronaut%20illustration&position=2&from_view=search"
          ><img
            src="{% static 'images/astro-2.png' %}"
            alt="astronaut-2"
            class="w-full"
        /></a>
      </div>

      <div>
        <a
          href="https://www.freepik.com/free-vector/astronaut-dabbing-cartoon-vector-icon-illustration-science-technology-icon-concept-isolated-premium-vector-flat-cartoon-style_16304150.htm#query=astronaut%20illustration&position=4&from_view=search"
          ><img
            src="{% static 'images/astro-3.png' %}"
            alt="astronaut-3"
            class="w-full"
        /></a>
      </div>

      <div>
        <a
          href="https://www.freepik.com/free-vector/cute-astronaut-flying-space-cartoon-icon-illustration_12681140.htm#query=astronaut%20illustration&position=43&from_view=search"
          ><img
            src="{% static 'images/astro-4.png' %}"
            alt="astronaut-4"
            class="w-full"
        /></a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

blogApp/templates/blogApp/blog.html
{% extends 'base.html' %} {% block title %}
<title>Blog</title>
{% endblock %} {% block content %}
<!-- this is the blog page -->
<div>
  <!-- this is the image of the blog post -->
  <div
    class="my-5 py-5 px-4 flex items-center h-72 bg-no-repeat bg-cover bg-center rounded-lg"
    style="
      background-image: url({{ item.image_url }});
    "
  ></div>
  <!-- this is the blog contents -->
  <!-- insert context data here -->
  <div class="px-4 py-4 text-gray-400 dark:text-gray-200">
    <h4 class="font-bold text-4xl text-gray-500 dark:text-gray-200">{{ item.title }}</h4>
    <h5 class="text-xs my-4">
      {{ item.timestamp }} by <strong class="dark:text-purple-500">{{ item.user_id.get_full_name }}</strong>
    </h5>
    <p class="text-md my-4 md:w-3/4">
      {{ item.body | safe }}
    </p>
  </div>
</div>
{% endblock %}

blogApp/templates/blogApp/blogs.html
{% extends 'base.html' %} {% block title %}
<title>Blogs</title>
{% endblock title %} {% block content %}
<div class="my-10">
  <!-- this is the blog section -->
  
  <div>
    <h2 class="font-bold text-6xl font-RobotoMono text-gray-700 dark:text-gray-200">The Blog</h2>
    <p class="my-4 md:w-1/2 font-Sanchez dark:text-gray-400">
      And here we are now, on the blog section of the website. <br />
      My blogs are a mix of articles of varying topics which you may find
      interesting as they are from the experiences of a frustrated programmer.
    </p>

    <!-- latest blogs -->
    
      <!-- *** insert the for loop here -->
    <div>
      {% include 'blogApp/includes/latest_blogs.html' %} 
    </div>
  
      <!-- *** endfor -->
  </div>
</div>
{% endblock content %}

blogApp/templates/blogApp/home.html
{% extends 'base.html' %} {% load static %} {% block title %}
<title>Mike Galindez | Home</title>
{% endblock %} {% block content %}
<!-- This is the hero section of the web app -->
<div class="grid sm:grid-cols-2 justify-center items-center mt-10">
  <div class="text-center sm:text-left">
    <h1 class="font-bold text-6xl text-gray-700 dark:text-gray-200 font-RobotoMono">Hi there busy Human!</h1>
    <h2 class="text-base my-5 dark:text-gray-400 font-Sanchez">
      I am Jerrson and welcome to my simple blog website. <br />
      You're free to critique, don't be shy.
    </h2>
    <div class="block my-5">
      <a
        href="{% url 'blogApp:blogs' %}"
        class="block sm:inline-block px-6 text-center font-RobotoMono bg-purple-600 text-white uppercase font-semibold py-3 rounded-lg hover:bg-purple-800 transition delay-200 hover:shadow-md hover:shadow-purple-500 dark:hover:shadow-purple-400 dark:hover:bg-purple-700"
        >Read my blogs</a
      >
    </div>
  </div>
  <div class="flex items-center justify-center">
    <img
      src="{% static 'images/main-astronaut.png' %}"
      alt="main-astronaut"
      class="max-w-xs"
    />
  </div>
</div>
<!-- here goes the recent blog items -->
        {% include 'blogApp/includes/featured_blogs.html' %}

{% endblock %}

blogApp/templates/blogApp/includes/blog_item.html
<!-- insert context data here -->
<div
  class="flex overflow-hidden rounded-lg shadow-lg bg-gray-50 hover:shadow-xl dark:bg-slate-700"
  data-aos="fade-up"
>
  <div>
    <img
      src="{{ item.image_url }}"
      alt="blog-img"
      class="object-cover w-52 h-full lg:w-72 hidden sm:block"
    />
  </div>
  <div class="px-4 py-4">
    <h4 class="font-bold text-xl font-RobotoMono">{{ item.title }}</h4>
    <h5 class="text-xs font-sans">
      {{ item.timestamp }} by <strong>{{ item.user_id.first_name }}</strong>
    </h5>
    <div class="text-gray-400">
      <p class="text-xs my-2">
        {{ item.body | safe | truncatechars_html:70 }}
        <a
          href="{% url 'blogApp:blog' item.id %}"
          class="text-purple-700 font-RobotoMono hover:text-purple-600 transition delay-150 font-semibold dark:text-purple-600 dark:hover:text-purple-400"
          >Read More</a
        >
      </p>
    </div>
    

    <!-- this is the tags on each blog item -->
    <div class="flex flex-wrap mt-2">
      {% for tag in item.tags.all %} {% include 'blogApp/includes/tag.html' %}
      {% endfor %}
    </div>
  </div>
</div>

blogApp/templates/blogApp/includes/empty_state.html
{% load static %}
<div class="text-center">
    <div>
        <img src="{% static 'images/empty-astronaut.png' %}" alt="empty-astronaut" class="w-1/4 mx-auto" />
        <h4>Oooppss.. sorry, its empty now</h4>
      </div>
      
</div>

blogApp/templates/blogApp/includes/featured_blogs.html
<section id="recent-blogs" class="my-16">
  <div>
    <!-- these are the recently added blog items -->
    <div class="">
      <h3 class="uppercase font-bold font-RobotoMono text-xl mb-3">Featured Blogs</h3>
      <hr class="w-1/4" />
    </div>

    <!-- blog cards container -->
    <div class="py-5 px-4">
      <!-- here goes blog cards -->
      <div class="grid gap-5 lg:grid-cols-2">
          {% for item in items %}
              {% include 'blogApp/includes/blog_item.html' %}
          <!-- This handles the empty state of the website -->
          {% empty %}
              <div class="col-span-3">
              {% include 'blogApp/includes/empty_state.html' %}
              </div>
          {% endfor %}
      </div>


    </div>

    <!-- this is the see more button -->
    <div class="block text-center my-3" data-aos="fade-up">
      <a
        href="{% url 'blogApp:blogs' %}"
        class="uppercase block font-RobotoMono sm:inline-block py-3 px-6 bg-purple-600 text-white font-semibold rounded-lg hover:bg-purple-800 hover:shadow-md hover:shadow-purple-500 transition delay-200 dark:shadow-purple-400 dark:hover:bg-purple-700"
        >Read more</a
      >
    </div>
  </div>
</section>

blogApp/templates/blogApp/includes/latest_blogs.html
<section id="latest-blogs" class="my-16">
  <div>
    <!-- these are the latest blogs-->
    <div class="">
      <h3 class="uppercase font-bold font-RobotoMono text-xl mb-3">Latest Blogs</h3>
      <hr class="w-1/4" />
    </div>

    
    <!-- the highlight blog goes here -->
    
    <div
      class="my-5 py-5 px-4 flex items-center h-72 bg-no-repeat bg-cover bg-center bg-blend-overlay bg-gray-700 rounded-lg overflow-hidden dark:bg-gray-600"
      style="
        background-image: url({{ latest_item.image_url }});
      "
    >
      <!-- insert context data here -->
      <div class="px-4 py-4 text-gray-100">
        <h4 class="font-bold text-xl">{{ latest_item.title }}</h4>
        <h5 class="text-xs">{{ latest_item.timestamp }} by <strong>{{ latest_item.user_id }}</strong></h5>
        <p class="text-sm my-2 md:w-3/4">
          {{ latest_item.body | safe | truncatechars_html:90 }}
        </p>
        <a href="{% url 'blogApp:blog' latest_item.id %}" class="text-purple-700 hover:text-purple-600 transition delay-150 font-semibold">Read More</a>
      </div>
    </div>


    <!-- blog cards container -->
    <div class="py-5 px-4">
      <!-- here goes blog cards -->
      <div class="grid gap-5 md:grid-cols-2">
        {% for item in items %}
          {% include 'blogApp/includes/blog_item.html' %}
        {% endfor %}
      </div>
    </div>
  </div>
</section>

blogApp/templates/blogApp/includes/recent_blogs.html
<section id="recent-blogs" class="my-16">
  <div>
    <!-- these are the recently added blog items -->
    <div class="">
      <h3 class="uppercase font-bold text-xl mb-3">Recent Blogs</h3>
      <hr class="w-1/4" />
    </div>

    <!-- blog cards container -->
    <div class="py-5 px-4">
      <!-- here goes blog cards -->
      <div class="grid gap-5 md:grid-cols-2">
          {% for item in items %}
              {% include 'blogApp/includes/blog_item.html' %}
          <!-- This handles the empty state of the website -->
          {% empty %}
              <div class="col-span-3">
              {% include 'blogApp/includes/empty_state.html' %}
              </div>
          {% endfor %}
      </div>


    </div>

    <!-- this is the see more button -->
    <div class="block text-center my-3">
      <a
        href="{% url 'blogApp:blogs' %}"
        class="uppercase block sm:inline-block py-3 px-6 bg-purple-600 text-white font-semibold rounded-lg hover:bg-purple-800 hover:shadow-md hover:shadow-purple-500 transition delay-200"
        >Read more</a
      >
    </div>
  </div>
</section>

blogApp/templates/blogApp/includes/tag.html
<!-- This is the tag of a blog post -->
<div class="bg-gray-200 py-2 px-3 font-sans rounded-full my-1 mr-1 dark:bg-purple-600">
    <h6 class="text-xs lowercase">{{ tag }}</h6>
</div>

templates/base.html
{% load static tailwind_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
        <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />

        {% block title %}
        {% endblock %}
	</head>
	<body class="bg-white leading-normal tracking-normal dark:bg-slate-800">
		{% include 'includes/navbar_component.html' %}
        <div class="min-h-screen px-10 py-7 text-gray-500 dark:text-gray-100 md:px-24 lg:px-44">
            {% block content %}
            {% endblock %}
        </div>
		
		{% include 'includes/footer.html' %}
		<script src="{% static 'js/base.js' %}"></script>
          <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
          <script>
            AOS.init();
          </script>
	</body>
</html>

templates/includes/footer.html
{% load static %}
<footer
  class="bg-gray-200 text-gray-600 font-medium font-RobotoMono px-10 py-5 dark:bg-slate-700 dark:text-gray-200"
>
  <div class="flex items-center justify-between">
    <!-- here goes the footer text -->
    <div>
      <h4>Made by Mike Jerrson Galindez</h4>
      <div class="flex mt-2">
        <a href="https://github.com/miker-bice" class="github">
          <!-- this is the github icon -->
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="fill-gray-700 mr-2 hover:fill-purple-600 transition delay-150 dark:fill-gray-200"
            width="24"
            height="24"
            viewBox="0 0 24 24"
          >
            <path
              d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"
            />
          </svg>
        </a>
        <a href="https://web.facebook.com/mikejerrson" class="facebook">
          <!-- this is the facebook icon -->
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="fill-gray-700 mr-2 hover:fill-purple-600 transition delay-150 dark:fill-gray-200"
            width="24"
            height="24"
            viewBox="0 0 24 24"
          >
            <path
              d="M12 0c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm3 8h-1.35c-.538 0-.65.221-.65.778v1.222h2l-.209 2h-1.791v7h-3v-7h-2v-2h2v-2.308c0-1.769.931-2.692 3.029-2.692h1.971v3z"
            />
          </svg>
        </a>
        <a href="https://www.linkedin.com/in/mj-galindez" class="linkedin">
          <!-- this is the linkedin icon -->
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="fill-gray-700 mr-2 hover:fill-purple-600 transition delay-150 dark:fill-gray-200"
            width="24"
            height="24"
            viewBox="0 0 24 24"
          >
            <path
              d="M12 0c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm-2 16h-2v-6h2v6zm-1-6.891c-.607 0-1.1-.496-1.1-1.109 0-.612.492-1.109 1.1-1.109s1.1.497 1.1 1.109c0 .613-.493 1.109-1.1 1.109zm8 6.891h-1.998v-2.861c0-1.881-2.002-1.722-2.002 0v2.861h-2v-6h2v1.093c.872-1.616 4-1.736 4 1.548v3.359z"
            />
          </svg>
        </a>
      </div>
    </div>

    <!-- here goes the illustration -->
    <div>
      <img
        src="{% static 'images/footer-astro.png' %}"
        alt="footer-astronaut"
        class="w-32 h-32"
      />
    </div>
  </div>
</footer>

templates/includes/navbar_component.html
<nav
  class="bg-gray-100 border-gray-200 px-10 py-3.5 rounded dark:bg-slate-700 font-RobotoMono"
>
  <div class="flex flex-wrap justify-between items-center">
    <a href="{% url 'blogApp:home' %}" class="flex items-center">
      <span
        class="self-center text-xl text-gray-700 font-bold whitespace-nowrap dark:text-white"
        >Mike Galindez</span
      >
    </a>
    <div class="flex md:order-2">
      <button
        type="button"
        class="text-white bg-purple-600 hover:bg-purple-800 focus:ring-4 focus:outline-none focus:ring-purple-500 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-3 md:mr-0 dark:bg-purple-600 dark:hover:bg-purple-800 transition delay-150"
      >
        Login
      </button>
      <button
        data-collapse-toggle="mobile-menu-4"
        type="button"
        id="mobile-menu-btn"
        class="inline-flex items-center p-2 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
        aria-controls="mobile-menu-4"
        aria-expanded="false"
      >
        <span class="sr-only">Open main menu</span>
        <svg
          class="w-6 h-6"
          fill="currentColor"
          viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill-rule="evenodd"
            d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
            clip-rule="evenodd"
          ></path>
        </svg>
        <svg
          class="hidden w-6 h-6"
          fill="currentColor"
          viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill-rule="evenodd"
            d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
            clip-rule="evenodd"
          ></path>
        </svg>
      </button>
    </div>
    <div
      class="hidden justify-between items-center w-full md:flex md:w-auto md:order-1"
      id="mobile-menu-4"
    >
      <ul
        class="flex flex-col mt-4 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium"
      >
        <li class="">
          <a
            href="{% url 'blogApp:home' %}"
            class="block py-2 pr-4 pl-3 text-gray-700 border-b hover:text-white border-gray-100 transition delay-200 hover:bg-purple-400 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-purple-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
            >Home</a
          >
        </li>
        <li>
          <a
            href="{% url 'blogApp:blogs' %}"
            class="block py-2 pr-4 pl-3 text-gray-700 border-b hover:text-white border-gray-100 transition delay-200 hover:bg-purple-400 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-purple-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
            >Blogs</a
          >
        </li>
        <li>
          <a
            href="{% url 'blogApp:about' %}"
            class="block py-2 pr-4 pl-3 text-gray-700 border-b hover:text-white border-gray-100 transition delay-200 hover:bg-purple-400 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-purple-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
            >About</a
          >
        </li>
      </ul>
    </div>
  </div>
</nav>

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>